server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/fbc?characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: kafka-chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.example.kafka_chat.chat
logging:
  level:
    org.springframework: INFO
    org.mybatis: DEBUG
    com.example.kafka_chat: DEBUG